# URL for git clone
GIT_URL=https://github.com/shockjiang/ndns

# Tag name or commit hash for checkout
GIT_VERSION=2c88d44be4668c19271151a5ad2cc4c09f4ad46f

# Package name
NAME=ndns

# Package version
VERSION=0.1.0

# PPA version
PPA_VERSION=1

include ../packaging.mk
